### PR TITLE
Backport PXC-3076: Galera build doesn't work with Python 3 (5.6)

### PR DESCRIPTION
**Pull request by venkatesh-prasad-v**
Issue:
The main SConstruct contains an incorrect Python 3 specific code
and results in an error.

  AttributeError: 'str' object has no attribute 'decode'

Fix:
Remove the python3 specific code and everything works with all scons
versions tested

(cherry picked from commit a3bc6ec232e7cc8ad5dba5f44898e007fb587725)

### CODE REVIEW

**Comment by venkatesh-prasad-v** [comment]
self approving as this is just the 8.0 port of https://github.com/percona/galera/pull/170

**Review by dutow — APPROVED** [review]
