### PR TITLE
PXC-3076: Galera build doesn't work with Python 3 (8.0)

### PR DESCRIPTION
**Pull request by dutow**
Issue:
The main SConstruct contains a (duplicated) Python 3 specific code,
which is actually incorrect, and results in an python: error.

  AttributeError: 'str' object has no attribute 'decode'

Fix:
Remove the python3 specific code and everything works with all scons
versions tested

(cherry picked from commit a3bc6ec232e7cc8ad5dba5f44898e007fb587725)

### CODE REVIEW

**Comment by dutow** [comment]
self approving as this is just the 8.0 port of #170
